server:
    port: 8090
    servlet:
        context-path: /
    error:
        path: /error

spring:
    mvc:
        throw-exception-if-no-handler-found: true
    web:
        resources:
            add-mappings: false
    cache:
        jcache:
            config: "classpath:ehcache.xml"
    application: 
        name: mce-project
    
    datasource:
        url: jdbc:mariadb://
        username: 
        password: 

domaine:
    gestion-recia:
        - lycees.netocentre.fr
        - cfa.netocentre.fr
        - www.chercan.fr
    gestion-include:
        - "0370074E"
        - "0410860M"
        - "0280957N"
        - "0180037T"
        - "0180766K"
        - "0360718K"
    gestion-exclude: []

jpa:
        show-sql: true 
        hibernate:
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
        

    ldap:
        base:
        urls:
            - ldap://
        username: 
        password: 

# management:
#   endpoints:
#     web:
#       exposure:
#         include:
#         - '*'

springdoc:
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
    api-docs:
        path: /v3/api-docs
        enabled: true
    # Si tu as Spring Security, autorise l'accès à Swagger
    packages-to-scan: fr.recia.mce.api.escomceapi.web.rest

logging:
    file:
        path:
    level:
        root: ERROR
        fr.recia.mce: DEBUG
        MCE_SPECIAL_LOGGER: INFO
    org.hibernate.SQL: ERROR

app:
    service:
        classe-properties: 
            ldap-attributs-classe:
            regex-siren-and-classe: 
            group-siren: 
            group-classe: 
            group-matiere: 
        grp-pedago--properties: 
            ldap-attributs-classe: 
            regex-siren-and-classe: 
            group-siren: 
            group-classe: 
            group-matiere: 
        custom-params:
            lien-edu: 
            lien-pass-etab: 
        relation-properties:
            regex-uid: 
            regex-relation: 
            group-uid: 
            group-typ-rel: 
            group-resp-finance: 
            group-resp-legal: 
            group-code-contact: 
            group-code-paiement: 
    ldap:
        user-branch:
            eleve-relation: 
            eleve-tuteur-entr: 
            tuteur-eleves: 
            eleve-enseignements: 
            code-matiere-enseignement: 
            other-displayed-attributes: 
            other-backend-attributes: 
        struct-branch:
            domaines: 
            name-struct: 
            structure-jointure: 
            skin: 
            type-struct: 
            uai: 
            ville: 
    
    soffit:
        jwt-signature-key: 


    avatar:
        # Remplacez 'lycees.test.recia.dev' par le domaine officiel de production
        # URL de base pour construire les liens des avatars et servir de modèle pour le stockage
        # Le frontend appellera cet endpoint pour récupérer l'image servie par Spring Boot
        base-url:
        # Répertoire physique sur le serveur où les fichiers images sont enregistrés
        storage-path:
        max-size: 524288
        allowed-types:
            - image/jpeg
            - image/png
            - image/jpg

mail:
    regexValideAddr: '[_A-Za-z0-9-]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)*(\.[A-Za-z-]{2,4})'
    regexsDomainesExclus: 'netocentre.fr touraine-eschool.fr chercan.fr colleges41.fr mon-e-college.loiret.fr e-college.indre.fr colleges-eureliens.fr'
    domainesConfiance: 'ac-orleans-tours.fr educagri.fr recia.fr'

    cors:
        enable: true
        allow-credentials: true
        allowed-origins: >
            http://localhost:5173
        exposed-headers:
            - x-auth-token
            - x-requested-with
            - x-xsrf-token
        allowed-headers:
            - content-type
            - authorization
            - x-com-persist
            - X-Auth-Token
            - x-auth-token
            - x-requested-with
            - x-xsrf-token
        allowed-methods:
            - GET
            - PUT
            - POST
            - DELETE